### ISSUE TITLE
not enough memory on nodemcu 0.9.6

### ISSUE THREAD

**Issue by spotrevoc** [marcoschwartz/aREST-ESP8266#1]
When I open a terminal and run dofile("basic.lua") it works okay but I want to have it start on boot so I created init.lua with only the dofile. With that I get a not enough memory error related to aREST.lua. I didn't have this problem at all on my other esp loaded with nodemcu 0.9.5.

**Comment by spotrevoc** [comment]
After flashing a few different versions, definitely want to use the 0.9.5 build 20150318 **INTEGER** binary.  Nothing else will allow for basic.lua/aREST.lua to be loaded at startup.
It can be found at https://github.com/nodemcu/nodemcu-firmware/releases
more specifically
https://github.com/nodemcu/nodemcu-firmware/releases/download/0.9.5_20150318/nodemcu_integer_0.9.5_20150318.bin

**Comment by marcoschwartz** [comment]
Interesting, thanks for letting us know. Note that I am now focusing all my efforts on aREST for the ESP8266 Arduino IDE (and it works!): https://github.com/marcoschwartz/aREST

**Comment by spotrevoc** [comment]
I can't get that to compile.

Interesting, thanks for letting us know. Note that I am now focusing all my
efforts on aREST for the ESP8266 Arduino IDE (and it works!):
https://github.com/marcoschwartz/aREST
